name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false   # para não sobrescrever o token
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .                     # ou './dist' se você fizer build
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
